version: '3'
services:

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./database:/home"

  backend:
    build: ../basic-webboard-backend
    depends_on:
      - mysql
    restart: always
    ports:
      - 5000:5000


  front:
    build: ../basic-webboard-frontend
    depends_on:
      - backend
    restart: always
    ports:
      - 3000:3000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
# networks:
#   backend:
#     driver: bridge
#   frontend:
#     driver: bridge



