version: '3.7'
services:

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .env

  nodejs:
    build: ../basic-webboard-backend
    depends_on:
      - db
    restart: always
    ports:
      - 5000:5000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - .env
    volumes:
      - ../basic-webboard-backend:/usr/src/app
      - /usr/src/app/node_modules

  react:
    build: ../basic-webboard-frontend
    depends_on:
      - nodejs
    restart: always
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - react.env
    volumes:
      - ../basic-webboard-frontend:/app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
