version: '3.7'
services:

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}     
    volumes:
      - ./database:/var/lib/mysql
      

  nodejs:
    build: ../basic-webboard-backend
    depends_on:
      - mysql
    restart: always
    ports:
      - 5000:5000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    
  react:
    build: ../basic-webboard-frontend
    depends_on:
      - nodejs
    restart: always
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"


# networks:
#   backend:
#     driver: bridge
#   frontend:
#     driver: bridge



